"""Streamlit entrypoint — the live demo surface.

Run: `streamlit run app.py`

What it does: loads the pipeline outputs from disk (no live Claude
calls) and renders a folium map with the 2,983 trench segments colored
by verdict. Click a segment → side panel with the photo grid, the
per-photo checks, and the human-readable reasons for the verdict.

Reads (everything from disk, regenerated by the pipeline):
    - data/processed/verdicts.csv
    - data/processed/geomatch.csv
    - data/processed/readqc.jsonl
    - data/geo/*.geojson

This file is the only one that imports streamlit. Keep pipeline modules
(src/*.py) headless — they run from `python -m src.<stage>` without UI.

Demo-day rule (CLAUDE.md): no live Claude calls during the pitch. All
the heavy work happens Saturday in the batch run; the app just reads
the cached results.
"""

from __future__ import annotations


def main() -> None:
    """Render the page. Imports streamlit lazily so the module imports cheap."""
    raise NotImplementedError("see PLAN.md → Killer demo moves + Data contracts")


if __name__ == "__main__":
    main()
