"""One place for every file path the pipeline reads or writes.

Importing `PATHS` from here means no stage hardcodes a string like
`"data/processed/geomatch.csv"`. If we ever move the data dir, we change
one line here, not seven.

If you need a path that isn't listed below, add it here first, then use it
in the stage module. Don't sprinkle Path() calls across the codebase.
"""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# --- Inputs (read-only, NDA-protected, gitignored under data/) ---
DATA_DIR = REPO_ROOT / "data"
PHOTOS_DIR = DATA_DIR / "Resources" / "all"
EXEMPLARS_DIR = DATA_DIR / "Beispiele" / "Beispiele"
GEO_DIR = DATA_DIR / "geo"
TRENCHES_GEOJSON = GEO_DIR / "CLP20417A-P1-B00_Trenches.geojson"
FCPS_GEOJSON = GEO_DIR / "CLP20417A-P1-B00_FCP_Polygons.geojson"
CLUSTER_GEOJSON = GEO_DIR / "CLP20417A-P1-B00_SiteCluster_Polygons.geojson"

# --- Outputs (gitignored, regenerated by the pipeline) ---
PROCESSED_DIR = DATA_DIR / "processed"
MANIFEST_DB = PROCESSED_DIR / "manifest.sqlite"
FORENSICS_JSONL = PROCESSED_DIR / "forensics.jsonl"
READQC_JSONL = PROCESSED_DIR / "readqc.jsonl"
READQC_FAILURES_JSON = PROCESSED_DIR / "readqc_failures.json"
GEOMATCH_CSV = PROCESSED_DIR / "geomatch.csv"
VERDICTS_CSV = PROCESSED_DIR / "verdicts.csv"

# --- Report bundle (handed to the partner) ---
REPORT_DIR = PROCESSED_DIR / "report"
DEFICIENCY_CSV = REPORT_DIR / "deficiency.csv"
NOT_CLASSIFIED_CSV = REPORT_DIR / "not_classified.csv"
PERSONAL_DATA_CSV = REPORT_DIR / "personal_data.csv"
SUMMARY_HTML = REPORT_DIR / "summary.html"


def ensure_dirs() -> None:
    """Create output directories. Safe to call at the top of any stage."""
    PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
